name: Automated Build
on:
    push: { branches: [master] }
    
env:
    UNITY_LICENSE: ${{secrets.UNITY_LICENSE_KEY}}
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./EndGame_Proto
        unityVersion:
          - 2019.3.3f1
        targetPlatform:
          - StandaloneWindows64
    steps:
        - name: Checkout Project
          uses: actions/checkout@v2
        
        # Cache
        - name: Caching
          uses: actions/cache@v1.1.0
          with:
            path: ${{ matrix.projectPath }}/Library
            key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
            restore-keys: |
              Library-${{ matrix.projectPath }}-
              Library-
        
        # Build Windows
        - name: Unity - Builder
          uses: webbertakken/unity-builder@v1.1
          with:
            projectPath: ${{matrix.projectPath}}
            unityVersion: ${{matrix.unityVersion}}
            targetPlatform: ${{matrix.targetPlatform}}
         
        - name: Archive Windows Build         
          uses: actions/upload-artifact@v1
          with:
            name: Build
            path: build